### ISSUE TITLE
Vafra is blinded? Move 78.

### ISSUE THREAD

**Issue by arturoiochoam** [RJurjevic/Vafra#1]
Hello,

I am running some tests at 2m3inc and I saw this weird game, I do not have the logs from Vafra. The game was balanced but suddenly Viafra makes a horrible blunder and got mated,

[Event "Vafra Files"]
[Site "13thIntel-i5-1335U.1300Mhz.10c-12t-Ram16G"]
[Date "2024.05.26"]
[Round "19"]
[White "Vafra 14.12.1 6t1024h"]
[Black "Avalanche 2.1.0 6t1024h"]
[Result "0-1"]
[ECO "B77"]
[Opening "Sicilian"]
[Time "20:55:21"]
[Variation "Dragon, Yugoslav, 9.Bc4 Bd7 10.Bb3"]
[TimeControl "120+3"]
[Termination "adjudication"]
[PlyCount "161"]
[WhiteType "program"]
[BlackType "program"]

1. e4 c5 2. Nc3 g6 3. Nf3 Nc6 4. d4 cxd4 5. Nxd4 Bg7 6. Be3 Nf6 7. Bc4 O-O
8. Bb3 d6 9. f3 {+0.37/29 8} Bd7 {-0.08/23 9} 10. Qd2 {+0.24/28 15} Nxd4
{-0.03/21 4} 11. Bxd4 {+0.13/28 4} b5 {0.00/25 5} 12. a4 {+0.11/26 12} b4
{-0.08/20 5} 13. Nd5 {+0.32/24 2} Nxd5 {-0.27/20 4} 14. Bxg7 {+0.35/29 10}
Kxg7 {-0.35/20 4} 15. exd5 {+0.29/30 4} a5 {-0.37/20 8} 16. h4 {+0.85/26 6}
h6 {-0.40/21 5} 17. Qd4+ {+0.96/22 3} Kg8 {-0.38/20 9} 18. Qe3 {+1.15/27
15} Kg7 {-0.47/21 8} 19. O-O-O {+0.98/26 9} Qe8 {-0.61/22 7} 20. h5
{+1.06/27 2} g5 {-0.55/20 4} 21. f4 {+0.96/25 10} g4 {-0.57/19 4} 22. Qd4+
{+0.82/29 33} f6 {-0.38/20 5} 23. Bc4 {+0.87/25 5} Bxa4 {-0.33/20 4} 24.
Bd3 {+1.03/24 2} Rc8 {-0.57/19 6} 25. Kb1 {+1.03/25 5} Bb5 {-0.44/21 11}
26. Rh4 {+1.09/25 7} Qd7 {-0.87/19 6} 27. f5 {+1.33/27 3} Kh8 {-0.71/21 4}
28. Rxg4 {+1.07/27 9} Bxd3 {-0.90/21 3} 29. Qxd3 {+0.97/26 6} Rf7 {-0.90/21
5} 30. Rg6 {+1.12/26 11} Rh7 {-0.66/21 7} 31. g4 {+1.37/24 1} Qc7 {-0.75/24
6} 32. b3 {+1.09/23 2} a4 {-0.69/24 8} 33. bxa4 {+1.25/25 1} Qa7 {-0.94/23
5} 34. Kb2 {+1.28/23 3} Qxa4 {-1.03/26 3} 35. Ra1 {+1.01/24 4} Qd7
{-1.05/26 2} 36. Ra6 {+1.38/22 3} Qb7 {-1.10/27 4} 37. Kb1 {+1.23/22 6} Rb8
{-1.12/24 4} 38. Rc6 {+1.19/20 5} b3 {-1.34/19 3} 39. cxb3 {+1.37/19 0} Qa7
{-1.36/24 6} 40. Qa6 {+1.64/20 2} Qxa6 {-1.33/13 4} 41. Rxa6 {+1.65/21 8}
Rxb3+ {-1.49/23 2} 42. Kc2 {+1.12/19 3} Rb8 {-1.28/24 3} 43. Ra7 {+1.57/22
6} Rf7 {-1.30/26 3} 44. Rxh6+ {+1.79/18 1} Kg7 {-1.29/26 2} 45. Rg6+
{+1.92/17 1} Kh8 {-1.30/23 4} 46. Kd3 {+1.79/19 2} Rb5 {-1.29/26 2} 47.
Ra8+ {+1.25/20 2} Kh7 {-1.30/26 2} 48. Kc4 {+2.05/17 0} Rc5+ {-1.27/23 2}
49. Kd4 {+1.15/20 5} Rc1 {-1.27/23 3} 50. Rgg8 {+0.89/22 4} Kh6 {-1.18/23
2} 51. Rg6+ {+1.11/19 2} Kh7 {-1.19/1 0} 52. Re8 {+0.81/24 3} Rc7 {-1.22/24
9} 53. Kd3 {+1.00/22 1} Rc1 {-1.11/27 2} 54. Rgg8 {+0.81/22 2} Kh6
{-1.11/27 2} 55. Rg6+ {+1.03/21 3} Kh7 {-1.56/1 0} 56. Kd4 {+0.86/24 3} Rc7
{-1.11/24 3} 57. Reg8 {+0.71/23 6} Rc2 {-1.11/28 3} 58. Rb8 {+0.89/20 1}
Rc7 {-1.11/25 9} 59. Rgg8 {+1.06/22 1} Kh6 {-1.11/25 3} 60. Rg6+ {+0.75/22
2} Kh7 {-1.85/1 0} 61. Re8 {+0.62/24 1} Rc2 {-1.09/24 3} 62. Rgg8 {+0.63/23
1} Kh6 {-1.10/23 2} 63. Rg6+ {+0.62/22 2} Kh7 {-1.30/1 0} 64. Rgg8
{+0.63/22 7} Kh6 {-1.09/23 2} 65. Ke3 {+0.52/18 1} Rc3+ {-1.09/24 3} 66.
Ke4 {+0.52/23 1} Rc4+ {-1.08/26 2} 67. Kd3 {+0.52/18 1} Rc1 {-1.08/21 2}
68. Ra8 {+0.42/245 10} Rc5 {-1.08/25 5} 69. Kd4 {+0.62/17 1} Rc1 {-1.08/22
5} 70. Rh8+ {+0.90/16 1} Kg5 {-0.61/20 2} 71. Rag8+ {+1.10/15 2} Kf4
{-0.19/23 2} 72. Rg6 {+1.26/16 3} e5+ {0.00/27 2} 73. fxe6 {+1.00/13 2}
Rd1+ {0.00/27 2} 74. Kc3 {+0.74/13 7} Rc7+ {0.00/32 3} 75. Kb3 {+0.51/11 3}
Rd3+ {0.00/33 3} 76. Kb2 {+0.48/12 1} Rd2+ {0.00/30 2} 77. Ka3 {+0.18/11 1}
Rd3+ {0.00/31 3} **78. Kb4 {+0.23/12 3}** Rb7+ {+M7/26 8} 79. Ka4 {-M6/27 1}
Rd1 {+M7/29 2} 80. Rxf6+ {-M5/86 1} Ke3 {+M5/91 2}  81. Rf3 {-M4/123 1 
Arena Adjudication} 0-1

**Comment by RJurjevic** [comment]
"Hello, thank you for reporting this issue. I tested Vafra 14.12.2 (the current development version) and, after clearing the hash table, Vafra made the correct move. It's unclear what went wrong initially; it could have been due to a shallow search, possibly because Vafra was running into time trouble." — Robert (rephrased by ChatGPT 4o)

![vafra_14 12 1_arturoiochoam-bug-1](https://github.com/RJurjevic/Vafra/assets/72772239/dcfe4332-dcd5-4724-8dcf-ef9542d39e1e)

**Comment by arturoiochoam** [comment]
To avoid Vafra going into time trouble I have increased the overhead time to 300ms. Also, here the recent results I got from the last version:

```
Vafra 14.12.2 6t1024h : Alexander 1.3 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :  22+  :  72=  :   6-  :   58.0%
Vafra 14.12.2 6t1024h : Alexander 2.0 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :  54+  :  45=  :   1-  :   76.5%
Vafra 14.12.2 6t1024h : Beast 15 6t1024h           :  100  :   0+  :  69=  :  31-  :   34.5%
Vafra 14.12.2 6t1024h : Cfish 12.6 6t1024h         :  100  :   2+  :  91=  :   7-  :   47.5%
Vafra 14.12.2 6t1024h : Chess-System-Tal 2.00.v21-E1019 6t1024h :  100  :   1+  :  90=  :   9-  :   46.0%
Vafra 14.12.2 6t1024h : Clover 6.2 6t1024h         :  100  :   5+  :  85=  :  10-  :   47.5%
Vafra 14.12.2 6t1024h : Clover 7.1 6t1024h         :  200  :   7+  : 173=  :  20-  :   46.75%
Vafra 14.12.2 6t1024h : Clover 8.0.1 6t1024h       :  200  :   4+  : 180=  :  16-  :   47.0%
Vafra 14.12.2 6t1024h : Coiled 1.2 6t1024h         :  100  :  48+  :  52=  :   0-  :   74.0%
Vafra 14.12.2 6t1024h : Fire 9.3 6t1024h           :  100  :   8+  :  84=  :   8-  :   50.0%
Vafra 14.12.2 6t1024h : HypnoS 120824 6t1024h      :  100  :   0+  :  75=  :  25-  :   37.5%
Vafra 14.12.2 6t1024h : HypnoS 140724 6t1024h      :  100  :   0+  :  82=  :  18-  :   41.0%
Vafra 14.12.2 6t1024h : INCOGNITO 8.2 6t1024       :  100  :   0+  :  75=  :  25-  :   37.5%
Vafra 14.12.2 6t1024h : Koivisto 9.2 6t1024h       :  100  :  12+  :  80=  :   8-  :   52.0%
Vafra 14.12.2 6t1024h : Lc0.cuda 0.31.1 611246.384 6t1024h :  100  :   5+  :  75=  :  20-  :   42.5%
Vafra 14.12.2 6t1024h : Lc0.cuda 0.31.1 722461.128 6t1024h :  100  :  24+  :  71=  :   5-  :   59.5%
Vafra 14.12.2 6t1024h : Lc0.cuda 0.31.1 731099.128 6t1024h :  100  :   7+  :  85=  :   8-  :   49.5%
Vafra 14.12.2 6t1024h : Lc0.cuda 0.31.1 744706.128 6t1024h :  100  :  16+  :  71=  :  13-  :   51.5%
Vafra 14.12.2 6t1024h : LittleBeast 15 6t1024h     :  100  :   0+  :  79=  :  21-  :   39.5%
Vafra 14.12.2 6t1024h : ShashChess 35.3 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :   0+  :  90=  :  10-  :   45.0%
Vafra 14.12.2 6t1024h : ShashChess 36 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :  11+  :  77=  :  12-  :   49.5%
Vafra 14.12.2 6t1024h : Stockfish 11 6t1024h       :  100  :  39+  :  58=  :   3-  :   68.0%
Vafra 14.12.2 6t1024h : Stockfish 12 6t1024h       :  100  :   1+  :  88=  :  11-  :   45.0%
Vafra 14.12.2 6t1024h : Stockfish 13 6t1024h       :  100  :   2+  :  90=  :   8-  :   47.0%
Vafra 14.12.2 6t1024h : Stockfish 14 6t1024h       :  100  :   3+  :  77=  :  20-  :   41.5%
Vafra 14.12.2 6t1024h : Stockfish 15.1 6t1024h     :  100  :   2+  :  81=  :  17-  :   42.5%
Vafra 14.12.2 6t1024h : Vafra 14.12.1 6t1024h      :  100  :   4+  :  95=  :   1-  :   51.5%
Vafra 14.12.2 6t1024h : Vanilla 15 6t1024h         :  100  :   0+  :  54=  :  46-  :   27.0%
```

**Comment by RJurjevic** [comment]
Hello, thanks for sharing the results. Are the percentages based on Vafra 14.12.2's performance? Please note that I have now transitioned to my Vafra Cfish clone. If you’re interested in testing it, I would recommend waiting until I release Cfish 12.7, which should be available in a few weeks. Also, could you clarify your test conditions? I run tests in a highly controlled environment, using 5-minute games with a 5-second increment, 6 threads on a 6-core ASUS gaming laptop.

**Comment by arturoiochoam** [comment]
Hello, Robert:

I hope this message finds you well! Next a summary of my test conditions so that you have a better understanding of my test environment:
- OS: Windows 11 Home.
- HW: 13th Gen Intel(R) Core(TM) i7-13700HX, Lenovo 5 Legion.
- Gui: Arena 3.5.1.
- Time Setup: 2m 5sc inc
- Gaunlet -Games by Match: 100.
- Ponder: Off.
- Hash Table: 1Gb.
- Threads: 6.
- Syzygy endgame tablebases 3,4,5 complete + most important 6,7.
- Ponder Off
- Opening Book: Different Opening Test Sets that I have collected by myself.

The %s are on Vafra 14.12.2 performance. Alll right, for your coming Cfish 12.7.

Let me know if you require any further information.

Best regards, Arthur Matheus.

PD: **Result Summary:**

```
Vafra 14.12.2 6t1024h : 

Alexander 1.3 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :  22+  :  72=  :   6-  :   58.0%
Alexander 2.0 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :  54+  :  45=  :   1-  :   76.5%
Beast 15 6t1024h           :  100  :   0+  :  69=  :  31-  :   34.5%
Brainlearn 29 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :   7+  :  70=  :  23-  :   42.0%
Cfish 12.6 6t1024h         :  100  :   2+  :  91=  :   7-  :   47.5%
Chess-System-Tal 2.00.v21-E1019 6t1024h :  100  :   1+  :  90=  :   9-  :   46.0%
Clover 6.2 6t1024h         :  100  :   5+  :  85=  :  10-  :   47.5%
Clover 7.1 6t1024h         :  200  :   7+  : 173=  :  20-  :   46.75%
Clover 8.0.2 6t1024h       :  200  :   4+  : 180=  :  16-  :   47.0%
Coiled 1.2 6t1024h         :  100  :  48+  :  52=  :   0-  :   74.0%
Fire 9.3 6t1024h           :  100  :   8+  :  84=  :   8-  :   50.0%
HypnoS 120824 6t1024h      :  100  :   0+  :  75=  :  25-  :   37.5%
HypnoS 140724 6t1024h      :  100  :   0+  :  82=  :  18-  :   41.0%
INCOGNITO 8.2 6t1024       :  100  :   0+  :  75=  :  25-  :   37.5%
Koivisto 9.2 6t1024h       :  100  :  12+  :  80=  :   8-  :   52.0%
Lc0.cuda 0.31.1 611246.384 6t1024h :  100  :   5+  :  75=  :  20-  :   42.5%
Lc0.cuda 0.31.1 722461.128 6t1024h :  100  :  24+  :  71=  :   5-  :   59.5%
Lc0.cuda 0.31.1 731099.128 6t1024h :  100  :   7+  :  85=  :   8-  :   49.5%
Lc0.cuda 0.31.1 744706.128 6t1024h :  100  :  16+  :  71=  :  13-  :   51.5%
LittleBeast 15 6t1024h     :  100  :   0+  :  79=  :  21-  :   39.5%
ShashChess 35.3 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :   0+  :  90=  :  10-  :   45.0%
ShashChess 36 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  200  :  15+  : 159=  :  26-  :   47.25%
Stockfish 11 6t1024h       :  100  :  39+  :  58=  :   3-  :   68.0%
Stockfish 12 6t1024h       :  100  :   1+  :  88=  :  11-  :   45.0%
Stockfish 13 6t1024h       :  100  :   2+  :  90=  :   8-  :   47.0%
Stockfish 14 6t1024h       :  100  :   3+  :  77=  :  20-  :   41.5%
Stockfish 15.1 6t1024h     :  100  :   2+  :  81=  :  17-  :   42.5%
Vafra 14.12.1 6t1024h      :  100  :   4+  :  95=  :   1-  :   51.5%
Vanilla 15 6t1024h         :  100  :   0+  :  54=  :  46-  :   27.0%

Vafra 14.12.1 6t1024h : 

Alexander 1.3 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  200  :  46+  : 147=  :   7-  :   59.75%
Avalanche 2.1.0 6t1024h    :  100  :  45+  :  54=  :   1-  :   72.0%
Chess-System-Tal 2.00.v21-E1019 6t1024h :  100  :   6+  :  89=  :   5-  :   50.5%
Clover 6.2 6t1024h         :  100  :   4+  :  88=  :   8-  :   48.0%
Coiled 1.2 6t1024h         :  100  :  40+  :  57=  :   3-  :   68.5%
Fire 9.3 6t1024h           :  100  :   9+  :  81=  :  10-  :   49.5%
HypnoS 140724 6t1024h      :  100  :   0+  :  68=  :  32-  :   34.0%
INCOGNITO 8.2 6t1024h      :  100  :   0+  :  73=  :  27-  :   36.5%
Koivisto 9.2 6t1024h       :  100  :   7+  :  83=  :  10-  :   48.5%
Komodo 10 6t1024h          :  100  :  60+  :  38=  :   2-  :   79.0%
Komodo 11.01 6t1024h       :  100  :  42+  :  55=  :   3-  :   69.5%
Komodo 12.1.1 6t1024h      :  100  :  36+  :  63=  :   1-  :   67.5%
Komodo 13 6t1024h          :  100  :  42+  :  54=  :   4-  :   69.0%
Komodo 14.1 6t1024h        :  100  :  33+  :  64=  :   3-  :   65.0%
Kuma 1.2 6t1024h           :  100  :  72+  :  28=  :   0-  :   86.0%
Lc0.OpenCl 0.31 BadGyal3.64 6t1024h :  100  :  89+  :  11=  :   0-  :   94.5%
Lc0.OpenCl 0.31.0-rc2 611246.384 6t1024h :  100  :  86+  :  14=  :   0-  :   93.0%
Lc0.OpenCl 0.31.0-rc3 42850.256 6t1024h :  100  :  92+  :   8=  :   0-  :   96.0%
Lc0.OpenCl 0.31.0-rc3 BadGyal2.128 6t1024h :  100  :  94+  :   6=  :   0-  :   97.0%
Lc0.OpenCl 0.31.0-rc3 LJ3.256 6t1024h :  100  :  92+  :   8=  :   0-  :   96.0%
Lc0.cuda 0.31.1 611246.384 6t1024h :  100  :   8+  :  88=  :   4-  :   52.0%
Lc0.onnx-dml 0.31.0 703810.128 6t1024h :  100  :  73+  :  26=  :   1-  :   86.0%
Lc0.onnx-dml 0.31.0 722461.128 6t1024h :  100  :  69+  :  31=  :   0-  :   84.5%
Lc0.onnx-dml 0.31.0 820625.512 6t1024h :  100  :  90+  :   9=  :   1-  :   94.5%
Lc0.onnx-dml 0.31.0 BadGyal4.128 6t1024h :  100  :  87+  :  13=  :   0-  :   93.5%
Lc0.onnx-dml 0.31.0 BadGyal5.128 6t1024h :  100  :  89+  :  10=  :   1-  :   94.0%
Lc0.onnx-dml 0.31.0 LD2(Little Demon 2).128 6t1024h :  100  :  80+  :  19=  :   1-  :   89.5%
Lc0.onnx-dml 0.31.1 715893.256 6t1024h :  100  :  59+  :  40=  :   1-  :   79.0%
Lc0.onnx-dml 0.31.1 785570.512 6t1024h :  100  :  39+  :  56=  :   5-  :   67.0%
Lc0.onnx-dml 0.31.1 LS15(Leelenstein 15.0).256 6t1024h :  100  :  95+  :   5=  :   0-  :   97.5%
LittleBeast 15 6t1024h     :  100  :   0+  :  58=  :  42-  :   29.0%
Raubfisch GTZ27e 6t1024h   :  100  :   0+  :  76=  :  24-  :   38.0%
Raubfisch X48e 6t1024h     :  100  :   0+  :  82=  :  18-  :   41.0%
Rebel 16.3 6t1024h         :  100  :   3+  :  86=  :  11-  :   46.0%
SFNN 9.6.3_240427 6t1024h  :  100  :   0+  :  68=  :  32-  :   34.0%
Seer 2.8 6t1024h           :  100  :   3+  :  93=  :   4-  :   49.5%
ShashChess 35.3 MCTS.1-PL.On-SS.AllOn-LiveBook.On.D255V0 6t1024h :  100  :   0+  :  76=  :  24-  :   38.0%
ShashChessPro 2.0 6t1024h  :  100  :  39+  :  58=  :   3-  :   68.0%
SteelFighter 6t1024h       :  100  :   0+  :  64=  :  36-  :   32.0%
Stockfish 10 6t1024h       :  100  :  37+  :  61=  :   2-  :   67.5%
Stockfish 11 6t1024h       :  100  :  36+  :  60=  :   4-  :   66.0%
Stockfish 12 6t1024h       :  100  :   6+  :  86=  :   8-  :   49.0%
Stockfish 13 6t1024h       :  100  :   7+  :  79=  :  14-  :   46.5%
Stockfish 14 6t1024h       :  100  :   3+  :  83=  :  14-  :   44.5%
Stockfish 14.1 6t1024h     :  100  :   0+  :  71=  :  29-  :   35.5%
Stockfish 15.1 6t1024h     :  100  :   1+  :  81=  :  18-  :   41.5%
StockfishDev 20240723 6t1024h :  100  :   0+  :  74=  :  26-  :   37.0%
Vafra 14.12.2 6t1024h      :  100  :   1+  :  95=  :   4-  :   48.5%
Vanilla 13.250523 6t1024h  :  100  :   1+  :  75=  :  24-  :   38.5%
Vanilla 14c 6t1024h        :  100  :   0+  :  72=  :  28-  :   36.0%
Vanilla 15 6t1024h         :  100  :   0+  :  66=  :  34-  :   33.0%

Vafra 14.12.1 8t4096h : 

EXchess 7.97b 8t4096h      :  100  :  98+  :   2=  :   0-  :   99.0%
Lc0.OpenCl 0.31.0.rc2 BadGyal1.20 8t4096h :  100  :  98+  :   2=  :   0-  :   99.0%
Lc0.OpenCl 0.31.0.rc2 SVt40.1573.384 8t4096h :  100  :  76+  :  24=  :   0-  :   88.0%
Raubfisch X48e 8t4096h     :  100  :   2+  :  84=  :  14-  :   44.0%
ShashChessPro 1.0 8t4096h  :  100  :  47+  :  53=  :   0-  :   73.5%
```

**Comment by arturoiochoam** [comment]
I will close this issue since it is resolved increasing the time overhead. Also awaiting the coming new version c-fish for testing.

**Comment by RJurjevic** [comment]
Hello arturoiochoam,

Thank you for the detailed information and thorough testing setup! Your hardware configuration with the Intel 13th Gen i7-13700HX on the Lenovo Legion 5 looks impressive, and the testing parameters are excellent. Having the 3-5 Syzygy tablebases along with select 6 and 7-piece setups and a 1GB hash size is a powerful configuration. I tend to favor a slightly longer time control, around 5m+5s, but your setup should certainly provide meaningful insights.

I noted that Vafra’s performance appeared below 50% against certain engines in your tables, which provides a useful point for comparison. Here are the specific matchups where it seemed to perform below this threshold (please feel free to confirm if I’m interpreting the results correctly):

**Vafra 14.12.2 (6t1024h):**

- Beast 15: 34.5%
- Brainlearn 29 MCTS: 42.0%
- Cfish 12.6: 47.5%
- Chess-System-Tal 2.00: 46.0%
- Clover 6.2: 47.5%
- Clover 7.1: 46.75%
- Clover 8.0.2: 47.0%
- HypnoS 120824: 37.5%
- HypnoS 140724: 41.0%
- INCOGNITO 8.2: 37.5%
- Lc0.cuda 611246.384: 42.5%
- LittleBeast 15: 39.5%
- ShashChess 35.3 MCTS: 45.0%
- ShashChess 36 MCTS: 47.25%
- Stockfish 12: 45.0%
- Stockfish 13: 47.0%
- Stockfish 14: 41.5%
- Stockfish 15.1: 42.5%
- Vanilla 15: 27.0%

**Vafra 14.12.1 (6t1024h):**

- Clover 6.2: 48.0%
- Fire 9.3: 49.5%
- HypnoS 140724: 34.0%
- INCOGNITO 8.2: 36.5%
- Koivisto 9.2: 48.5%
- LittleBeast 15: 29.0%
- Raubfisch GTZ27e: 38.0%
- Raubfisch X48e: 41.0%
- Rebel 16.3: 46.0%
- SFNN 9.6.3_240427: 34.0%
- ShashChess 35.3 MCTS: 38.0%
- SteelFighter: 32.0%
- Stockfish 12: 49.0%
- Stockfish 13: 46.5%
- Stockfish 14: 44.5%
- Stockfish 14.1: 35.5%
- Stockfish 15.1: 41.5%
- StockfishDev 20240723: 37.0%
- Vanilla 13.250523: 38.5%
- Vanilla 14c: 36.0%
- Vanilla 15: 33.0%

As for the notation `6t1024h` and `8t4096h`, I interpret these as indicating "6 threads with 1024 MB hash" and "8 threads with 4096 MB hash," respectively. Thanks again for sharing these results—they’re very insightful!

P.S. yes, please close the issue, thanks 

P.P.S. the new Cfish 12.7 shall be the strongest, of all of my Vafras, retraining the last net, if not good, then will use the best so far, will retest, and then release

**Comment by arturoiochoam** [comment]
I can use your time setup but I will need to decrease the matches to 50 games.
